### ISSUE TITLE
SyntaxError -- parens not closed

### ISSUE THREAD

**Issue by erikcw** [ets/tap-spreadsheets-anywhere#29]
Just tried testing my configuration and found a syntax error:

```
% meltano config tap-spreadsheets-anywhere test
2022-12-19T22:03:05.353237Z [info     ] Environment 'dev' is active
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

Plugin configuration is invalid
Catalog discovery failed: command ['/Users/erik/Dropbox/home/git/meltano-projects/s3-inventory/.meltano/extractors/tap-spreadsheets-anywhere/venv/bin/tap-spreadsheets-anywhere', '--config', '/Users/erik/Dropbox/home/git/meltano-projects/s3-inventory/.meltano/run/tap-spreadsheets-anywhere/tap.29fe46e1-3e31-443c-bcc4-8baf31f11e37.config.json', '--discover'] returned 1 with stderr:
 Traceback (most recent call last):
  File "/Users/erik/Dropbox/home/git/meltano-projects/s3-inventory/.meltano/extractors/tap-spreadsheets-anywhere/venv/bin/tap-spreadsheets-anywhere", line 5, in <module>
    from tap_spreadsheets_anywhere import main
  File "/Users/erik/Dropbox/home/git/meltano-projects/s3-inventory/.meltano/extractors/tap-spreadsheets-anywhere/venv/lib/python3.10/site-packages/tap_spreadsheets_anywhere/__init__.py", line 12, in <module>
    import tap_spreadsheets_anywhere.conversion as conversion
  File "/Users/erik/Dropbox/home/git/meltano-projects/s3-inventory/.meltano/extractors/tap-spreadsheets-anywhere/venv/lib/python3.10/site-packages/tap_spreadsheets_anywhere/conversion.py", line 10
    t_schema = pickle.loads(pickle.dumps((schema))
                           ^
SyntaxError: '(' was never closed

```
https://github.com/ets/tap-spreadsheets-anywhere/blob/master/tap_spreadsheets_anywhere/conversion.py#L10

**Comment by erikcw** [comment]
Looks like it was introduced in the PR #18 today.

**Comment by ets** [comment]
Just patched - thx.
